[package]
name = "git_user_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
dirs = "6.0.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
